### ISSUE TITLE
Seeking new maintainer!

### ISSUE THREAD

**Issue by leeper** [cloudyr/aws.iam#10]
This package is not being actively maintained. If you're interested in contributing or taking over, please express your interest here.

**Comment by jonthegeek** [comment]
Just discovered that these packages were removed from CRAN! I know you had this up for over a year, but I *might* be interested. I'm way not an expert in aws, but these packages made some tasks easy for me, so I'd like to help. Mostly I'm wondering how painful it was to run these and what I'm volunteering for 😃

**Comment by maelle** [comment]
Should this information (seeking new maintainer) be at the top of the README too?

**Comment by s-u** [comment]
@acolum after taking over `aws.s3` (which is now happily on CRAN) I'd like to volunteer for `aws.iam` and `aws.kms` as well. Ideally, could you, please, add me to the `cloudyr` team so I can help with such issues on the other projects? Thanks.
@jonthegeek if you so desire, you can be the maintainer - if someone actively handles PRs then that's fine with me, too, I just want to see those packages to get fixed and get back on CRAN.

**Comment by acolum** [comment]
@s-u   Unfortunately, I don't have the permissions required to add you to the `cloudyr` team, but @leeper, @hrbrmstr, and @MarkEdmondson1234 appear to, as they each have the "Owner" role in `cloudyr`.

**Comment by s-u** [comment]
@acolum thanks for your prompt response. It's not urgent, as long as there is an active member like you I don't really need it. If you have access (I can't see whether you do), could you, please, add me as contributor to to `aws.iam` and `aws.kms` if there is no objection? Thanks.

**Comment by acolum** [comment]
@s-u No problem. I don't have access to `aws.iam` and `aws.kms`, so I unfortunately can't add you as a contributor to either of those repositories.

**Comment by MarkEdmondson1234** [comment]
I have invited @s-u to a KMS and IAM team: https://github.com/orgs/cloudyr/teams/aws-iam-and-kms - thanks!

**Comment by MarkEdmondson1234** [comment]
@s-u is an admin now so please comment if you want to be added as a maintainer too - sorry I didn't get the notifications from the thread previously.  It would be good to have a team of people for each if they can contribute.

**Comment by s-u** [comment]
Thanks, @MarkEdmondson1234 , much appreciated.
To all, if anyone wants to still volunteer as a maintainer or contributor, please do so.
If you think that's too much, you can also contribute with PRs etc. - I'll be handling those in the meantime.

**Comment by jonthegeek** [comment]
Thank you so much! I'll still try to contribute, but I'm very glad to see someone else making sure these packages live!
