### ISSUE TITLE
IAM Roles (Instance Metadata Service)

### ISSUE THREAD

**Issue by dolendupes** [cloudyr/aws.iam#6]
For authentication, is it possible to use the instance metadata service on an Amazon EC2 instance that has an IAM role configured?  It would be nice to leverage the facility in Amazon for managing credentials, rather than having to manually configure the environment/code.

**Comment by leeper** [comment]
Yes, this is forthcoming in the [aws.signature](https://github.com/cloudyr/aws.signature) package but is not yet on CRAN. You can also access that metadata using the [aws.ec2metadata](https://cran.r-project.org/web/packages/aws.ec2metadata/index.html) in the meantime.

**Comment by dolendupes** [comment]
Thanks.  Look forward to when this feature is added.
