### ISSUE TITLE
feature request: helper function to set environment credentials from role

### ISSUE THREAD

**Issue by phlogisticfugu** [cloudyr/aws.iam#8]
To assist with bootstrapping credentials in different environments, it is helpful to be able to explicitly load temporary credentials from AWS STS into R environment variables.

This lets one control for explicitly which role to get credentials for.  The problem with the calls to `aws.signature::locate_credentials` within various other functions is that one cannot pass a role.

Also, storing the temporary credentials within environment variables leads to better performance when doing many API requests that require credentials.

suggested usage:
```R
res <- aws.iam::set_temp_role_creds_in_env('$myrole$')
# res == TRUE if successful
# writes to AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN

# then one can do:
aws.s3::s3SaveRDS(mtcars, object = 'test.Rds', bucket = '$mybucket$')
# and know that the specific role is being used
```

**Comment by phlogisticfugu** [comment]
would be happy to write a PR to implement this if its welcome.  am also up for a better name for this function

**Comment by joshua-morten** [comment]
@phlogisticfugu I am interested in this. Do you have something mocked up already?

**Comment by s-u** [comment]
You can do this already:
```r
r <- assume_role("arn:aws:iam::111111111111:role/my-role", "test")
saveRDS(r, file="role-cred.rds")
```
in another session:
```r
r <- readRDS("role-cred.rds")
set_credentials(r)
```
unless I'm missing something?
